server:
  port: 3333
  
spring:
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  application:
    name: maps-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
info:
  app:
    name: Rideforce Map Service
    description: This is the map service for the Rideforce Map.

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
