server:
  port: 3333
  
spring:
  datasource:
    url: jdbc:oracle:thin:@rideshare-maps-rds.chueiwozbnfz.us-east-1.rds.amazonaws.com:1521/ORCL
    username: rideshare_maps_rds
    password: ride2r3v
    driver-class-name: oracle.jdbc.driver.OracleDriver
  application:
    name: maps-service
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update

info:
  app:
    name: Rideshare Map Service
    description: This is the map service for the Rideshare Map.

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka