server:
  port: 3333
  
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: demo
    password: demo
    driver-class-name: oracle.jdbc.driver.OracleDriver
  application:
    name: maps-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

info:
  app:
    name: Rideforce Map Service
    description: This is the map service for the Rideforce Map.

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka